# -*- coding: utf-8 -*-
"""CIS3400_Week1_Colab_Quick_Start_Penguins_ML_FINALipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OJF6k5SuEaDGUTVra4kIm9je6PBbmdi1

# CIS 3400 Advanced Programming
## Week 1: Google Colab Quick Start — Exploring Penguins

#

**Name:** *Type your name here*

Welcome to your first notebook for Advanced Programming!

In this short activity, you will practice using **Google Colab** while working with a real dataset. You will:

- run Python code in notebook cells,
- import Python libraries,
- read data into a pandas DataFrame,
- explore a dataset,
- create a visualization,
- write and use a simple function, and
- add Markdown notes to explain what you observe.

### How to work in Colab
Click a code cell and press the **Run** button (▶) or press **Shift + Enter**.

Work from the top of the notebook to the bottom so that variables and imports are created before later cells use them.

> **Instructor note:** All completed answers in this key are marked **ANSWER**. Numbers were produced with `random_state=42` and the seaborn-data copy of the Palmer Penguins CSV. Small differences are possible if scikit-learn or pandas versions change.

## 1. Import Python Libraries

Python libraries give us tools that have already been written for common programming tasks.

We will use:

- **pandas** for working with tabular data
- **matplotlib** for creating visualizations
"""

import pandas as pd
import matplotlib.pyplot as plt

print("Libraries imported successfully!")

"""## 2. Read a Real Dataset

We will use the **Palmer Penguins** dataset. It contains measurements for penguins from three species observed in Antarctica.

The code below reads a CSV file from the web and stores it in a pandas **DataFrame** named `df`.

A DataFrame is similar to a table or spreadsheet: it has rows and columns.
"""

url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/penguins.csv"
df = pd.read_csv(url)

print("Data loaded!")

"""## 3. Take a Look at the Data

`head()` displays the first few rows of a DataFrame.
"""

df.head()

"""Now let's find out how large the dataset is.

`shape` returns:

**(number of rows, number of columns)**
"""

df.shape

"""### YOUR TURN #1

In the Markdown cell below, record how many **rows** and **columns** are in the dataset.

**My answer:** *(ANSWER)*

`df.shape` returns `(344, 7)`.

Rows: **344**
Columns: **7**

The 7 columns are `species`, `island`, `bill_length_mm`, `bill_depth_mm`, `flipper_length_mm`, `body_mass_g`, and `sex`.

## 4. Explore the Data

`describe()` gives us summary statistics for the numeric columns.
"""

df.describe()

"""Notice that `describe()` reports a **count of 342**, not 344, for every numeric column. Two penguins are missing all of their measurements. We will deal with that in Section 9.

We can also see how many penguins belong to each species.
"""

df["species"].value_counts()

"""### YOUR TURN #2

Change `"species"` in the code below to `"island"` and run the cell.

How many penguins were observed on each island?
"""

df["island"].value_counts()

"""**My answer:** *(ANSWER)*

| Island | Penguins |
|---|---|
| Biscoe | 168 |
| Dream | 124 |
| Torgersen | 52 |

The three islands add up to 344, which matches the row count from YOUR TURN #1. Biscoe has more than three times as many penguins as Torgersen, so the islands are not evenly sampled.

## 5. Filter the Data

We can select only rows that meet a condition.

The code below creates a new DataFrame containing only **Adelie** penguins.
"""

adelie = df[df["species"] == "Adelie"]

adelie.head()

"""### YOUR TURN #3

Change `"Adelie"` to either `"Gentoo"` or `"Chinstrap"` and run the cell again.
"""

# ANSWER — same pattern, different species
gentoo = df[df["species"] == "Gentoo"]

print("Number of Gentoo penguins:", len(gentoo))
gentoo.head()

# ANSWER — and for Chinstrap
chinstrap = df[df["species"] == "Chinstrap"]

print("Number of Chinstrap penguins:", len(chinstrap))
chinstrap.head()

"""**My answer:** *(ANSWER)*

Filtering to `"Gentoo"` returns **124** rows and filtering to `"Chinstrap"` returns **68** rows. Those match the counts we got from `value_counts()` in Section 4, which is a good sanity check: the filter is doing exactly what the count told us to expect.

Notice that every Gentoo row shows `Biscoe` in the `island` column. That is a real pattern in the data, not a coincidence, and it will show up again when we look at feature importance.

## 6. Create a Visualization

Let's look at the relationship between a penguin's **flipper length** and **body mass**.

A scatter plot is useful when we want to compare two numeric variables.
"""

df.plot.scatter(
    x="flipper_length_mm",
    y="body_mass_g",
    title="Penguin Flipper Length vs. Body Mass"
)

plt.show()

"""### What do you notice?

Add **one sentence** below describing something you notice in the graph.

**My observation:** *(ANSWER)*

Penguins with longer flippers are heavier — the points rise from lower left to upper right, so flipper length and body mass increase together.

*Anything along these lines earns full credit. Other reasonable observations:*

- The points appear to form **two loose clusters**: one below about 210 mm and 4,500 g, and a second, heavier group above it.
- The relationship is strong but **not perfect** — at any given flipper length there is still a spread of several hundred grams.
- The correlation between the two columns is **0.87**, which you can confirm with `df[["flipper_length_mm", "body_mass_g"]].corr()`.
"""

# ANSWER — optional: color the same plot by species to see where the clusters come from
for species_name, group in df.groupby("species"):
    plt.scatter(
        group["flipper_length_mm"],
        group["body_mass_g"],
        label=species_name,
        alpha=0.7
    )

plt.xlabel("flipper_length_mm")
plt.ylabel("body_mass_g")
plt.title("Flipper Length vs. Body Mass, by Species")
plt.legend()
plt.show()

print(df[["flipper_length_mm", "body_mass_g"]].corr().round(3))

"""The upper cluster is almost entirely **Gentoo**. Adelie and Chinstrap overlap heavily with each other in this view. Keep that in mind — it comes back in Section 9.

## 7. Write a Simple Function

Functions let us package code into a reusable operation.

The dataset records body mass in **grams**. Let's write a function that converts grams to kilograms.
"""

def grams_to_kg(grams):
    return grams / 1000

"""Now call the function:"""

grams_to_kg(5000)

"""We can even use the function with a value from our dataset."""

first_penguin_mass = df.loc[0, "body_mass_g"]

print("Mass in grams:", first_penguin_mass)
print("Mass in kilograms:", grams_to_kg(first_penguin_mass))

"""### YOUR TURN #4

Call `grams_to_kg()` with a value of your choice.
"""

# ANSWER — any numeric value is acceptable
grams_to_kg(3750)

# ANSWER — going a step further: apply the function to a whole column at once
# (built as a separate view so we don't permanently change df)
mass_comparison = df[["species", "body_mass_g"]].copy()
mass_comparison["body_mass_kg"] = df["body_mass_g"].apply(grams_to_kg)

mass_comparison.head()

"""**My answer:** *(ANSWER)*

`grams_to_kg(3750)` returns **3.75**, because the function divides by 1000.

Any value the student picks is fine here. The point of the exercise is that the function works on a number we typed in, on a value pulled out of the DataFrame, or on an entire column — we wrote the logic once and reused it three different ways.

## 8. One Last Look

Let's display the average numeric measurements for each penguin species.
"""

df.groupby("species").mean(numeric_only=True)

"""*(ANSWER — what to point out here)*

| Species | bill_length_mm | bill_depth_mm | flipper_length_mm | body_mass_g |
|---|---|---|---|---|
| Adelie | 38.79 | 18.35 | 189.95 | 3700.66 |
| Chinstrap | 48.83 | 18.42 | 195.82 | 3733.09 |
| Gentoo | 47.50 | 14.98 | 217.19 | 5076.02 |

Read across the rows and you can already see how a model will tell these apart:

- **Adelie** has by far the shortest bill (38.8 mm vs. roughly 48 mm for the other two).
- **Gentoo** has the shallowest bill (15.0 mm) and is much larger overall.
- **Chinstrap** and **Gentoo** have similar bill *lengths*, but very different bill *depths*.

No single measurement separates all three species, but any two of them together nearly do.

## 9. Build a Predictive Model

So far we have described the penguins we already measured.

Now we will build a **machine learning model** that tries to predict something we do *not* already know: given a penguin's measurements, which **species** is it?

The idea is simple:

1. Show the model a set of penguins where we already know the species (the **training** data).
2. Hide a second set of penguins from it (the **testing** data).
3. Ask the model to predict the species of the hidden penguins.
4. Compare its predictions to the real answers and score how well it did.

We are previewing an idea here that we will study in depth later in the semester. For today, focus on *reading* the code and being able to say what each line is doing.

### 9.1 Import the Machine Learning Tools

`scikit-learn` (imported as `sklearn`) is Python's standard machine learning library. It is already installed in Colab.
"""

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import roc_auc_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import ConfusionMatrixDisplay

print("Machine learning tools imported!")

"""### 9.2 Handle the Missing Values

Look back at row 3 of the dataset. Several columns contain `NaN`, which means the value is **missing**.

A model cannot train on missing values, so we need to deal with them. The simplest option is to drop any row that has a missing value.

`dropna()` returns a new DataFrame with those rows removed.
"""

model_df = df.dropna()

print("Rows before dropping missing values:", len(df))
print("Rows after dropping missing values: ", len(model_df))
print("Rows removed:", len(df) - len(model_df))

"""*(ANSWER — expected output)*

```
Rows before dropping missing values: 344
Rows after dropping missing values:  333
Rows removed: 11
```

Eleven rows go away: 2 penguins missing every measurement, and 9 more missing only `sex`. Dropping is the quick answer for Week 1 — later in the course we will talk about *imputing* missing values instead, and about why dropping rows can quietly bias a dataset.

### 9.3 Choose the Target and the Features

Two terms we will use all semester:

- The **target** (`y`) is the thing we are trying to predict. Here it is `species`.
- The **features** (`X`) are the pieces of information the model gets to look at.

One complication: a model does math, so it cannot work with text like `"Biscoe"` or `"MALE"` directly. `pd.get_dummies()` converts each text category into its own True/False column. This is called **one-hot encoding**.
"""

target_column = "species"

feature_columns = [
    "island",
    "bill_length_mm",
    "bill_depth_mm",
    "flipper_length_mm",
    "body_mass_g",
    "sex"
]

y = model_df[target_column]
X = model_df[feature_columns]

# Turn the text columns into numeric True/False columns
X = pd.get_dummies(X, columns=["island", "sex"])

X.head()

"""Notice that `island` and `sex` are gone, replaced by a set of new columns.

Note that `species` is **not** in `X`. If we gave the model the answer as a feature, it would score perfectly and would have learned nothing.
"""

print("Number of features:", X.shape[1])
print()
print("Feature names:")
for name in X.columns:
    print(" -", name)

"""*(ANSWER — expected output)*

**9 features:** `bill_length_mm`, `bill_depth_mm`, `flipper_length_mm`, `body_mass_g`, `island_Biscoe`, `island_Dream`, `island_Torgersen`, `sex_FEMALE`, `sex_MALE`.

We started with 6 columns. The 4 numeric ones passed through untouched; `island` became 3 columns and `sex` became 2, so 2 text columns turned into 5 numeric ones.

### 9.4 Split the Data into Training and Testing Sets

We hold back part of the data so we can test the model on penguins it has never seen.

- `test_size=0.25` holds back 25% of the rows for testing.
- `random_state=42` makes the split reproducible, so everyone in class gets the same result.
- `stratify=y` keeps the mix of species roughly the same in both halves.
"""

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.25,
    random_state=42,
    stratify=y
)

print("Training rows:", len(X_train))
print("Testing rows: ", len(X_test))
print()
print("Species in the training set:")
print(y_train.value_counts())
print()
print("Species in the testing set:")
print(y_test.value_counts())

"""*(ANSWER — expected output)*

**249 training rows** and **84 testing rows**, which together account for all 333 rows.

| Species | Training | Testing |
|---|---|---|
| Adelie | 109 | 37 |
| Gentoo | 89 | 30 |
| Chinstrap | 51 | 17 |

That is `stratify=y` doing its job. Each species holds roughly the same share in both halves — Adelie is about 44% of the training rows and about 44% of the testing rows. Without stratification, a random split could easily have handed us a test set with very few Chinstraps, and our scores would then depend more on luck than on the model.

### 9.5 Train the Model

We will use a **Random Forest**, which builds a large collection of decision trees and lets them vote on the answer.

`fit()` is the step where the model actually learns. It only ever sees the training data.
"""

model = RandomForestClassifier(n_estimators=200, random_state=42)

model.fit(X_train, y_train)

print("Model trained!")
print("Species this model can predict:", model.classes_)

"""### 9.6 Make Predictions

`predict()` returns the single species the model thinks is most likely.

`predict_proba()` returns the model's confidence in *each* species. We need those probabilities later to compute AUC.
"""

y_pred = model.predict(X_test)
y_proba = model.predict_proba(X_test)

# Put the real answers and the predictions side by side
comparison = pd.DataFrame({
    "actual": y_test.values,
    "predicted": y_pred
})

comparison.head(10)

# ANSWER — instead of eyeballing 10 rows, count the disagreements directly
mistakes = comparison[comparison["actual"] != comparison["predicted"]]

print("Test penguins:", len(comparison))
print("Mistakes:", len(mistakes))
mistakes

"""*(ANSWER)*

**Zero mistakes.** Every one of the 84 test penguins was classified correctly, so `mistakes` comes back as an empty DataFrame. Hold that thought until YOUR TURN #5.

### 9.7 Evaluate the Model

Now we score the predictions against the real answers. Each metric answers a slightly different question:

- **Accuracy** — of all the test penguins, what fraction did we get right?
- **Precision** — when the model said "Gentoo," how often was it actually a Gentoo?
- **Recall** — of all the real Gentoos, how many did the model find?
- **F1 score** — a single number that balances precision and recall.
- **AUC** — how well the model separates one species from the others across all confidence levels. 1.0 is perfect, 0.5 is a coin flip.

Because we have three species instead of two, we ask for the `macro` average, which computes the metric for each species and then averages them, treating all three species as equally important.

AUC needs one extra argument for the same reason. With only two possible answers, AUC can read a single column of probabilities. With three, we pass the whole `y_proba` array and set `multi_class="ovr"` — "one versus rest" — which scores each species against the other two and then averages the results.
"""

print("Accuracy :", round(accuracy_score(y_test, y_pred), 3))
print("Precision:", round(precision_score(y_test, y_pred, average="macro"), 3))
print("Recall   :", round(recall_score(y_test, y_pred, average="macro"), 3))
print("F1 score :", round(f1_score(y_test, y_pred, average="macro"), 3))
print("AUC      :", round(roc_auc_score(y_test, y_proba, multi_class="ovr", average="macro"), 3))

"""We can also get precision, recall, and F1 broken out **for each species** in one table.

The `support` column tells us how many test penguins of that species there were.
"""

print(classification_report(y_test, y_pred))

"""### YOUR TURN #5

In the Markdown cell below, record the accuracy and the AUC, then answer this question:

Does a score this high make you trust the model *more* or *less*? Why?

**My answer:** *(ANSWER)*

Accuracy: **1.000**
AUC: **1.000**

Precision, recall, and F1 are all 1.000 as well. The model got all 84 test penguins right.

**What I think about that score:** it makes me trust the model **less**, or at least it makes me want to check my work before I trust it. A perfect score is a red flag, not a trophy. When I see one, there are three things to rule out:

1. **Did the answer leak into the features?** This is the first thing to check. If `species` had accidentally been left in `X`, the model would score 1.000 by simply reading the answer off the input. We checked — it isn't in there.
2. **Is the test set too small or too easy?** Only 17 Chinstraps ended up in the test set. Getting 17 of 17 right is genuinely good, but it is much weaker evidence than getting 1,700 of 1,700 right.
3. **Is the problem just easy?** In this case, yes. Section 8 already showed us that Adelie has a much shorter bill and Gentoo has a much shallower bill, so the three species are nearly separable by two measurements. This is a clean, curated teaching dataset with three physically distinct species — that is not what real data usually looks like.

Here the answer is #3, which is the harmless one. But we only know that because we checked. **A perfect score is a prompt to investigate, not a reason to stop.**

*Grading note: full credit for "less," plus any reasonable explanation. A student who answers "more" and gives a thoughtful defense should get partial credit and a comment — the instinct to be pleased by a high score is the exact instinct this section is designed to complicate.*

### 9.8 Confusion Matrix

A **confusion matrix** shows exactly *where* the model was right and where it was wrong.

Read it like this: each **row** is the species a penguin really was, and each **column** is the species the model guessed. Correct predictions land on the diagonal running from the top left to the bottom right. Anything off that diagonal is a mistake.
"""

cm = confusion_matrix(y_test, y_pred, labels=model.classes_)

# As a table
cm_table = pd.DataFrame(cm, index=model.classes_, columns=model.classes_)
print("Rows = actual species, Columns = predicted species")
print(cm_table)

display = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=model.classes_
)

display.plot(cmap="Blues")
plt.title("Confusion Matrix: Actual vs. Predicted Species")
plt.show()

"""*(ANSWER — expected output)*

```
           Adelie  Chinstrap  Gentoo
Adelie         37          0       0
Chinstrap       0         17       0
Gentoo          0          0      30
```

Every count sits on the diagonal and every off-diagonal cell is 0, which is what a 1.000 accuracy looks like drawn out. The plot shows the same thing: three dark squares running corner to corner, everything else empty.

This is worth seeing precisely because it is boring. In Section 9.11 we will build a model that makes real mistakes, and the contrast between the two matrices is the lesson.

### 9.9 Feature Importance

The model can tell us which features it leaned on most when making its decisions.

`feature_importances_` gives one number per feature. They add up to 1.0, so a feature with an importance of 0.35 accounted for about 35% of the model's decision making.
"""

importances = pd.Series(model.feature_importances_, index=X.columns)
importances = importances.sort_values(ascending=False)

print(importances.round(3))

importances.sort_values().plot.barh(
    title="Which measurements mattered most?"
)

plt.xlabel("Importance")
plt.tight_layout()
plt.show()

"""### YOUR TURN #6

Which feature was the most important? Which was the least important?

Look back at the scatter plot in Section 6. Does the ranking match what you saw there?

**My answer:** *(ANSWER)*

The full ranking:

| Feature | Importance |
|---|---|
| bill_length_mm | 0.346 |
| flipper_length_mm | 0.256 |
| bill_depth_mm | 0.133 |
| island_Dream | 0.082 |
| island_Biscoe | 0.079 |
| body_mass_g | 0.076 |
| island_Torgersen | 0.019 |
| sex_FEMALE | 0.005 |
| sex_MALE | 0.004 |

**Most important feature:** `bill_length_mm` (0.346)
**Least important feature:** `sex_MALE` (0.004)

**Does this match the scatter plot?** Partly, and the mismatch is the interesting part.

- **What matches:** `flipper_length_mm` ranks second. The scatter plot showed a distinct upper cluster, and Section 8 tells us why — Gentoo averages 217 mm compared to about 190–196 mm for the other two. Flipper length is doing real work, exactly as the picture suggested.
- **What doesn't match:** `body_mass_g` was one of the two axes of that scatter plot, yet it ranks sixth at 0.076 — below two of the island columns. And `bill_length_mm`, the single most important feature, **doesn't appear in the scatter plot at all.**

The lesson: the plot we happened to draw showed us two variables, and it was easy to assume those were the two that mattered. The model looked at all nine and found that the most useful signal was in a column we never plotted. Body mass and flipper length correlate at 0.87, so once the model knows the flipper length, body mass adds very little new information — the two are largely telling it the same thing.

`sex` barely registers because male and female penguins of the same species overlap heavily in size. Hold onto that fact — Section 9.11 turns it around and asks the model to predict `sex` instead.

### 9.10 Predict a Brand New Penguin

A model is only useful if we can hand it something new.

Below we invent a penguin that is not in the dataset and ask the model to classify it.

One detail matters here: the new penguin has to be described with **exactly the same columns, in the same order**, that the model was trained on. `reindex()` lines the columns up and fills in any missing category column with 0.
"""

new_penguin = pd.DataFrame([{
    "island": "Biscoe",
    "bill_length_mm": 45.0,
    "bill_depth_mm": 15.0,
    "flipper_length_mm": 220.0,
    "body_mass_g": 5200.0,
    "sex": "MALE"
}])

# Encode it the same way we encoded the training data
new_penguin = pd.get_dummies(new_penguin, columns=["island", "sex"])
new_penguin = new_penguin.reindex(columns=X.columns, fill_value=0)

prediction = model.predict(new_penguin)[0]
probabilities = pd.Series(model.predict_proba(new_penguin)[0], index=model.classes_)

print("Predicted species:", prediction)
print()
print("How confident the model is:")
print(probabilities.round(3))

"""*(ANSWER — expected output)*

```
Predicted species: Gentoo

Adelie       0.000
Chinstrap    0.000
Gentoo       1.000
```

All 200 trees voted Gentoo. That makes sense: a shallow bill (15.0 mm), a long flipper (220 mm), and a heavy body (5,200 g) on Biscoe island is a textbook Gentoo profile. There is nothing ambiguous about this penguin.

### YOUR TURN #7

Change the measurements above to describe a different penguin and run the cell again.

Can you find a set of measurements where the model is **not** confident, meaning no single species gets a probability close to 1.0?
"""

# ANSWER — a helper so we can test several penguins quickly
def classify_penguin(island, bill_length, bill_depth, flipper_length, body_mass, sex):
    row = pd.DataFrame([{
        "island": island,
        "bill_length_mm": bill_length,
        "bill_depth_mm": bill_depth,
        "flipper_length_mm": flipper_length,
        "body_mass_g": body_mass,
        "sex": sex
    }])
    row = pd.get_dummies(row, columns=["island", "sex"])
    row = row.reindex(columns=X.columns, fill_value=0)

    probs = pd.Series(model.predict_proba(row)[0], index=model.classes_)
    print("Predicted:", model.predict(row)[0], " | confidence:", round(probs.max(), 3))
    print(probs.round(3).to_string())
    print()


# A confident penguin: clearly Gentoo
print("--- Clearly Gentoo ---")
classify_penguin("Biscoe", 47.0, 15.0, 218.0, 5000.0, "MALE")

# An ambiguous penguin: sits right on the Adelie / Chinstrap boundary
print("--- Ambiguous ---")
classify_penguin("Dream", 42.5, 16.0, 200.0, 3900.0, "MALE")

"""**My answer:** *(ANSWER)*

Yes. This penguin splits the forest almost down the middle:

| Measurement | Value |
|---|---|
| island | Dream |
| bill_length_mm | 42.5 |
| bill_depth_mm | 16.0 |
| flipper_length_mm | 200.0 |
| body_mass_g | 3900.0 |
| sex | MALE |

```
Predicted: Chinstrap  | confidence: 0.435

Adelie       0.420
Chinstrap    0.435
Gentoo       0.145
```

The model still has to name a winner, and it says Chinstrap — but only 87 of the 200 trees agreed. Adelie got 84. A prediction that arrives with 43.5% confidence is a very different thing from one that arrives with 100% confidence, and `predict()` alone would never have told us the difference.

**How to find an ambiguous case:** put the measurements *between* the species averages from Section 8. A 42.5 mm bill sits between Adelie's 38.8 mm and Chinstrap's 48.8 mm; a 16.0 mm bill depth sits between Gentoo's 15.0 mm and the other two at roughly 18.4 mm. A penguin that doesn't look like any of the three groups will confuse the model, and a penguin that sits squarely inside one group won't.

**The takeaway:** always look at `predict_proba()`, not just `predict()`. A model that is 43% sure and a model that is 100% sure produce the same single answer, and in a real application — a medical screen, a fraud flag, a loan decision — that difference should change what you do next.

### 9.11 A Score That Is Too Good

Our first model scored **perfectly**: accuracy 1.000, AUC 1.000, not one mistake in 84 test penguins. That should raise an eyebrow, not a cheer. Real-world data is rarely that tidy, and a perfect score usually means the problem was easy, not that the model was brilliant.

Here the problem really is easy. The three species have noticeably different bills and flippers, so they are simple to tell apart — Section 8 showed us that before we trained anything at all.

To see what a normal score looks like, let's keep the **exact same data, the exact same model, and the exact same code**, and change only one thing: instead of predicting the species, we will predict the penguin's **sex**.

That is a genuinely harder question. Male penguins tend to be a bit larger than females of the same species, but the two overlap a great deal, so there is no clean dividing line for the model to find.
"""

# Same rows, same model settings. Only the target changes.
y_sex = model_df["sex"]

sex_feature_columns = [
    "bill_length_mm",
    "bill_depth_mm",
    "flipper_length_mm",
    "body_mass_g",
    "species",
    "island"
]

X_sex = model_df[sex_feature_columns]
X_sex = pd.get_dummies(X_sex, columns=["species", "island"])

X_sex_train, X_sex_test, y_sex_train, y_sex_test = train_test_split(
    X_sex,
    y_sex,
    test_size=0.25,
    random_state=42,
    stratify=y_sex
)

sex_model = RandomForestClassifier(n_estimators=200, random_state=42)
sex_model.fit(X_sex_train, y_sex_train)

y_sex_pred = sex_model.predict(X_sex_test)
y_sex_proba = sex_model.predict_proba(X_sex_test)

print("What this model can predict:", sex_model.classes_)
print()
print("Accuracy :", round(accuracy_score(y_sex_test, y_sex_pred), 3))
print("Precision:", round(precision_score(y_sex_test, y_sex_pred, pos_label="MALE"), 3))
print("Recall   :", round(recall_score(y_sex_test, y_sex_pred, pos_label="MALE"), 3))
print("F1 score :", round(f1_score(y_sex_test, y_sex_pred, pos_label="MALE"), 3))
print("AUC      :", round(roc_auc_score(y_sex_test, y_sex_proba[:, 1]), 3))
print()
print(classification_report(y_sex_test, y_sex_pred))

"""Notice two small changes in the code above.

Because there are only **two** possible answers now, we no longer need `average="macro"` — instead we tell precision, recall, and F1 which class counts as the positive one with `pos_label="MALE"`. And AUC goes back to reading a single column of probabilities, `y_sex_proba[:, 1]`, with no `multi_class` argument.

This is worth pausing on: the *metric* did not change, only the *shape* of the problem did. Two-class and three-class problems are scored with the same ideas but slightly different arguments.
"""

cm_sex = confusion_matrix(y_sex_test, y_sex_pred, labels=sex_model.classes_)

print("Rows = actual sex, Columns = predicted sex")
print(pd.DataFrame(cm_sex, index=sex_model.classes_, columns=sex_model.classes_))
print()

ConfusionMatrixDisplay(
    confusion_matrix=cm_sex,
    display_labels=sex_model.classes_
).plot(cmap="Oranges")

plt.title("Confusion Matrix: Actual vs. Predicted Sex")
plt.show()

# ANSWER — where do the mistakes fall? Break the errors out by species.
sex_results = pd.DataFrame({
    "actual": y_sex_test.values,
    "predicted": y_sex_pred,
    "species": model_df.loc[X_sex_test.index, "species"].values
})
sex_results["correct"] = sex_results["actual"] == sex_results["predicted"]

print(sex_results.groupby("species")["correct"].agg(["sum", "count", "mean"]).round(3))
print()
print("The six penguins the model got wrong:")
print(sex_results[~sex_results["correct"]])

"""### Discussion

*(ANSWER — expected results and what to draw out)*

**The scores dropped, and that is the point.**

| Metric | Predicting species | Predicting sex |
|---|---|---|
| Accuracy | 1.000 | 0.929 |
| F1 | 1.000 | 0.930 |
| AUC | 1.000 | 0.963 |

Same 333 penguins, same Random Forest, same `random_state=42`, same 249/84 split. The only thing that changed was the question we asked.

**The confusion matrix:**

```
        FEMALE  MALE
FEMALE      38     4
MALE         2    40
```

Six mistakes out of 84 — four females called male, two males called female. Compare that to Section 9.8, where every off-diagonal cell was 0.

**Discussion questions and answers:**

- **Is 0.929 a bad score?** No — it is a *believable* score. Predicting a penguin's sex from four body measurements and getting it right 93% of the time is a real result. The 1.000 from Section 9 told us almost nothing except that the species were far apart to begin with.

- **Where do the mistakes fall?** Not evenly. Broken out by species, the model gets **Adelie** right 31 of 32 times (96.9%) and **Gentoo** 34 of 36 (94.4%), but **Chinstrap** only 13 of 16 (81.2%). Three of the six errors are Chinstraps, even though Chinstraps are the smallest group in the test set. The single headline accuracy number completely hides that.

- **Which features did the model use?** Run `pd.Series(sex_model.feature_importances_, index=X_sex.columns).sort_values(ascending=False)` and you get `bill_depth_mm` (0.298) and `body_mass_g` (0.298) at the top, with the species and island columns near zero. That matches the biology: within any species, males have deeper bills and more mass. It is also a nice mirror of Section 9.9, where `bill_depth_mm` mattered much less and `sex` mattered almost not at all. **The same column can be crucial for one question and useless for another.** Importance is a property of the question, not of the column.

- **Why does the AUC (0.963) sit higher than the accuracy (0.929)?** Accuracy only asks whether the final answer was right. AUC looks at the underlying probabilities and asks whether the model ranked males above females overall. A model can rank well and still land on the wrong side of the 0.5 cutoff for a handful of borderline penguins — which is exactly what happened to those six.

**The lesson for the whole semester:** we never judge a model by a single number. Accuracy hides *which* cases fail. The per-class report and the confusion matrix are what reveal it, and knowing which cases fail is usually what determines whether a model is safe to actually use.

## Finished!

You have now used Google Colab to:

- run Python code,
- import libraries,
- load a CSV file,
- explore a pandas DataFrame,
- filter data,
- make a visualization,
- write a function,
- document your work using Markdown,
- train a predictive model, and
- evaluate that model and inspect its mistakes.

### Submit in Blackboard

Before submitting:

1. Make sure your **name** is at the top.
2. Make sure you completed all **YOUR TURN** sections.
3. From Colab, choose **File → Download → Download .ipynb**.
4. Submit the `.ipynb` file in Blackboard.

**Grading:** Completion and reasonable effort.

---

### Instructor answer summary

| Item | Answer |
|---|---|
| YOUR TURN #1 | 344 rows, 7 columns |
| YOUR TURN #2 | Biscoe 168, Dream 124, Torgersen 52 |
| YOUR TURN #3 | Gentoo 124 rows, Chinstrap 68 rows |
| Section 6 observation | Positive relationship, r = 0.87; two clusters, upper one is Gentoo |
| YOUR TURN #4 | Any value; `grams_to_kg(3750)` → 3.75 |
| Species model | Accuracy 1.000, Precision 1.000, Recall 1.000, F1 1.000, AUC 1.000 |
| YOUR TURN #5 | Trust it **less** — perfect scores prompt an investigation (leakage? small test set? easy problem?) |
| YOUR TURN #6 | Most: `bill_length_mm` (0.346). Least: `sex_MALE` (0.004). Only a partial match to the scatter plot |
| YOUR TURN #7 | Dream / 42.5 / 16.0 / 200.0 / 3900.0 / MALE → Chinstrap at 0.435 confidence |
| Sex model (9.11) | Accuracy 0.929, F1 0.930, AUC 0.963; 6 errors (4 FEMALE→MALE, 2 MALE→FEMALE) |
| Sex model by species | Adelie 96.9%, Gentoo 94.4%, Chinstrap 81.2% |

**Two corrections made to the original notebook:**

1. Section 9.3 had `target_column = "sex"` with `species` in the feature list, which contradicted the surrounding narrative ("we are predicting species," "`species` is not in `X`," "`island` and `sex` are gone"). Restored to `target_column = "species"` with `island` and `sex` as one-hot features. This also makes Section 9.10 correct, since that cell already encodes `["island", "sex"]`.

2. Section 9.7 computed AUC as `roc_auc_score(y_test, y_proba[:, 1])`, which raises an error on a three-class target. Changed to `roc_auc_score(y_test, y_proba, multi_class="ovr", average="macro")`.

Section 9.11 was rebuilt as the sex-prediction contrast described above, replacing the earlier two-weak-features variant.
"""